(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for long() with base 10: 'Rory'"
p3
sS'layer'
p4
S'C:\\Web2Py\\web2py_win\\web2py\\applications\\BootUp\\controllers/profile.py'
p5
sS'code'
p6
S"\n@auth.requires_login(otherwise=URL('default','login'))\ndef profile():\n\n    user = (db(db.auth_user.id == auth._get_user_id()).select())[0]\n    useless = (db(db.auth_user.username == user.address_id).select())\n    number_of_projects = db(db.project.username == user.first_name).select()\n    #number_of_pledges = db(db.pledges.username == user.username).select()\n\n\n    return dict(user=user,)\n\nresponse._vars=response._caller(profile)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "gluon/restricted.py", line 224, in restricted\n  File "C:\\Web2Py\\web2py_win\\web2py\\applications\\BootUp\\controllers/profile.py", line 13, in <module>\n  File "gluon/globals.py", line 392, in <lambda>\n  File "gluon/tools.py", line 3439, in f\n  File "C:\\Web2Py\\web2py_win\\web2py\\applications\\BootUp\\controllers/profile.py", line 7, in profile\n    number_of_projects = db(db.project.username == user.first_name).select()\n  File "gluon/dal.py", line 10749, in select\n  File "gluon/dal.py", line 2472, in select\n  File "gluon/dal.py", line 1868, in select\n  File "gluon/dal.py", line 1767, in _select\n  File "gluon/dal.py", line 1544, in expand\n  File "gluon/dal.py", line 1440, in EQ\n  File "gluon/dal.py", line 1555, in expand\n  File "gluon/dal.py", line 2012, in represent\nValueError: invalid literal for long() with base 10: \'Rory\'\n'
p11
s.